trigger:
- master

jobs:
- job: build
  strategy:
    matrix:
      linux:
        imageName: ubuntu-18.04
      mac:
        imageName: macos-10.15
      windows:
        imageName: windows-2019

  pool:
    vmImage: $(imageName)

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 12.x
    displayName: Install Node.js

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - bash: |
      echo ">>> Install dependencies"
      npm ci
      echo ">>> Compile"
      npm compile
      echo ">>> Lint"
      npm run lint
      echo ">>> Test"
      npm test
    displayName: Run Tests
    env:
      DISPLAY: :99.0

- job: release
  dependsOn: build

  strategy:
    matrix:
      linux:
        imageName: ubuntu-18.04

  pool:
    vmImage: $(imageName)

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 12.x
    displayName: Install Node.js

  - bash: |
      echo ">>> Build extension"
      npm ci
      npm install -g vsce
      vsce package
      git tag -f latest
      git push -f https://$(PAT)@github.com/jozefs/VSNotes latest
      mv *vsix vsnotes-latest.vsix

  - task: CopyFiles@2
    inputs:
      contents: vsnotes-latest.vsix
      targetFolder: $(Build.ArtifactStagingDirectory)
      cleanTargetFolder: true

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: vsnotes-release
      repositoryName: $(Build.Repository.Name)
      action: edit
      target: $(Build.SourceVersion)
      tagSource: manual
      tag: latest
      assets: $(Build.ArtifactStagingDirectory)/vsnotes-latest.vsix
      isPreRelease: true
      addChangeLog: false
    displayName: Upload extension to GitHub
